# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8db1cba59ffc7c9000459be47704eaa48b50b5366e40af5ad150d7529892b2d540ecd9443b70c39b24b3a1ef0dbb5974fcf9446415573fb2f8f5cc35e78de81

test:
  secret_key_base: 2452a78a1dfd533da29e2da72e1becfdff81fb1265f7ee7cbc9178db29a7b64025da7933f3faeb631e41dcb13b23b23ea1aa9b264ed88dc4b9eaf79cda6cd2c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
